ALTER TABLE `Post` MODIFY `title` VARCHAR(191) NOT NULL DEFAULT '';
ALTER TABLE `Post` MODIFY `dek` TEXT NULL;
ALTER TABLE `Post` MODIFY `excerpt` TEXT NULL;
ALTER TABLE `Post` MODIFY `bodyHtml` MEDIUMTEXT NULL;
ALTER TABLE `Post` MODIFY `coverImageUrl` VARCHAR(2048) NULL;
ALTER TABLE `Post` MODIFY `readMinutes` INTEGER NOT NULL DEFAULT 1;
